# Docker Compose file for nzb stack
version: "3"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/sabnzbd:/config
      - ${rootDL}:/downloads #optional
    ports:
      - 8080:8080 # 8080 is default
    restart: unless-stopped
    network_mode: bridge
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/sonarr:/config
      - ${rootMedia}:/media #optional
      - ${rootDL}:/downloads #optional
    ports:
      - 8989:8989 # 8989 is default
    restart: unless-stopped
    network_mode: bridge
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/radarr:/config
      - ${rootMedia}:/media #optional
      - ${rootDL}:/downloads #optional
    ports:
      - 7878:7878 # 7878 is default
    restart: unless-stopped
    network_mode: bridge
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/lidarr:/config
      - ${rootMedia}:/media #optional
      - ${rootDL}:/downloads #optional
    ports:
      - 8686:8686 # 8686 is default
    restart: unless-stopped
    network_mode: bridge
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - PUID=${uid}
      - PGID=${gid}
      - TZ=${tz}
    volumes:
      - ${rootConf}/bazarr:/config
      - ${rootMedia}:/media #optional
    ports:
      - 6767:6767 # 6767 is default
    restart: unless-stopped
    network_mode: bridge
